#' calcIPriceFuelsIntBase
#'
#' Unlike iPriceFuelsInt, which includes several fossil fuel categories,
#' iPriceFuelsIntBase retains only the international price series for crude
#' oil (WCRO) and natural gas (WNGS). These fuels are selected from the
#' complete fuel price dataset generated by calcOutput(type = "IPriceFuelsInt",
#' aggregate = FALSE).
#'
#' The resulting dataset provides the baseline international fuel price
#' trajectories for crude oil and natural gas used in OPEN-PROM, expressed
#' in $2015/toe and returned as a MAgPIE object.
#'
#' @return magpie object with OPENPROM input data iPriceFuelsIntBase.
#'
#' @author Anastasis Giannousakis, Fotis Sioutas, Giannis Tolios
#'
#' @examples
#' \dontrun{
#' a <- calcOutput(type = "IPriceFuelsIntBase", aggregate = FALSE)
#' }
#'
#' @importFrom dplyr %>% select mutate left_join case_when if_else arrange
#' @importFrom quitte as.quitte interpolate_missing_periods
#' @importFrom utils tail

calcIPriceFuelsIntBase <- function() {

  x <- calcOutput(type = "IPriceFuelsInt", aggregate = FALSE)

  # Only keeping prices for crude oil and natural gas
  fuels <- c("WCRO", "WNGS")
  x <- x[, , fuels]

  list(x = x,
       weight = NULL,
       unit = "$2015/toe",
       description = "IEA; Fossil Fuel Prices")
}
